#!/bin/bash
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report1 | sed '1d' > formatted_output_data/feature_format_report1
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100003 | sed '1d' > formatted_output_data/feature_format_report100003
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100008 | sed '1d' > formatted_output_data/feature_format_report100008
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100013 | sed '1d' > formatted_output_data/feature_format_report100013
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100015 | sed '1d' > formatted_output_data/feature_format_report100015
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100017 | sed '1d' > formatted_output_data/feature_format_report100017
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100030 | sed '1d' > formatted_output_data/feature_format_report100030
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100031 | sed '1d' > formatted_output_data/feature_format_report100031
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100040 | sed '1d' > formatted_output_data/feature_format_report100040
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report100045 | sed '1d' > formatted_output_data/feature_format_report100045
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report14 | sed '1d' > formatted_output_data/feature_format_report14
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report16 | sed '1d' > formatted_output_data/feature_format_report16
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report19 | sed '1d' > formatted_output_data/feature_format_report19
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report22 | sed '1d' > formatted_output_data/feature_format_report22
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report24 | sed '1d' > formatted_output_data/feature_format_report24
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report25 | sed '1d' > formatted_output_data/feature_format_report25
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report3 | sed '1d' > formatted_output_data/feature_format_report3
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report47 | sed '1d' > formatted_output_data/feature_format_report47
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report50 | sed '1d' > formatted_output_data/feature_format_report50
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report51 | sed '1d' > formatted_output_data/feature_format_report51
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report52 | sed '1d' > formatted_output_data/feature_format_report52
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report54 | sed '1d' > formatted_output_data/feature_format_report54
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report58 | sed '1d' > formatted_output_data/feature_format_report58
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report61 | sed '1d' > formatted_output_data/feature_format_report61
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report65 | sed '1d' > formatted_output_data/feature_format_report65
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report76 | sed '1d' > formatted_output_data/feature_format_report76
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report77 | sed '1d' > formatted_output_data/feature_format_report77
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report94 | sed '1d' > formatted_output_data/feature_format_report94
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report95 | sed '1d' > formatted_output_data/feature_format_report95
crf_test -v1 -m word_model_04_1 formatted_test_data/feature_format_report98 | sed '1d' > formatted_output_data/feature_format_report98
